# Generated by Django 3.2.3 on 2022-03-28 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('practice', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('tariff', models.IntegerField()),
                ('approval', models.CharField(max_length=50)),
                ('svm', models.IntegerField()),
                ('logistics', models.IntegerField()),
                ('bayes', models.IntegerField()),
                ('knn', models.IntegerField()),
                ('trees', models.IntegerField()),
                ('forest', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claim.account')),
            ],
        ),
    ]
