# Generated by Django 3.2.3 on 2022-03-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_claim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterField(
            model_name='claim',
            name='bayes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='forest',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='knn',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='logistics',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='svm',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='trees',
            field=models.CharField(max_length=50),
        ),
    ]
