# Generated by Django 3.2.3 on 2022-03-31 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0005_claim_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
