# Generated by Django 3.2.3 on 2022-05-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0006_remove_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='bayes',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='knn',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='logistics',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='svm',
        ),
        migrations.AddField(
            model_name='claim',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
